[package]
name = "ferrix-kernel"
description = "The Ferrix kernel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "ferrix-kernel"
path = "src/main.rs"

[dependencies]
ferrix-acpi.workspace = true
ferrix-blkring.workspace = true
ferrix-devmgr-proto.workspace = true
ferrix-block.workspace = true
ferrix-bootinfo.workspace = true
ferrix-btrfs.workspace = true
ferrix-btrfs-vfs.workspace = true
ferrix-btrfs-write.workspace = true
ferrix-description.workspace = true
ferrix-fdt.workspace = true
ferrix-fbtext.workspace = true
ferrix-frame.workspace = true
ferrix-elf.workspace = true
ferrix-fallible.workspace = true
ferrix-heap.workspace = true
ferrix-kmem.workspace = true
ferrix-linux-abi.workspace = true
ferrix-net.workspace = true
ferrix-netring.workspace = true
ferrix-displayctl.workspace = true
ferrix-renderctl.workspace = true
ferrix-inputctl.workspace = true
ferrix-sndctl.workspace = true
ferrix-chardevctl.workspace = true
ferrix-logctl.workspace = true
ferrix-audit.workspace = true
ferrix-netwire.workspace = true
ferrix-netlink.workspace = true
ferrix-nettcp.workspace = true
ferrix-native-abi.workspace = true
ferrix-objects.workspace = true
ferrix-paging.workspace = true
ferrix-partition.workspace = true
ferrix-pci.workspace = true
ferrix-procfs.workspace = true
ferrix-cgroupfs.workspace = true
ferrix-sysfs.workspace = true
ferrix-qr.workspace = true
ferrix-crng.workspace = true
ferrix-sched.workspace = true
ferrix-seccomp.workspace = true
ferrix-sync.workspace = true
ferrix-ustack.workspace = true
ferrix-vdso.workspace = true
ferrix-vfs.workspace = true
ferrix-virtio.workspace = true
ferrix-vma.workspace = true

[lints]
workspace = true
